### ISSUE TITLE
Flag not found on Mac

### ISSUE THREAD

**Issue by ddliugit** [humanoid-path-planner/hpp-fcl#63]
I installed Pinocchio on Mac. When I try to import  Pinocchio in the python2, I met the following error:

ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pinocchio/libpinocchio_pywrap.so, 2): Symbol not found: __ZN5boost6system16generic_categoryEv
  Referenced from: /usr/local/lib/libhpp-fcl.dylib
  Expected in: /usr/local/opt/boost/lib/libboost_system-mt.dylib
 in /usr/local/lib/libhpp-fcl.dylib

I guess this is caused by the library of hpp-fcl or the boost, though I have tried many times to install these two packages with latest home-brew. Can you help me out?

**Comment by jcarpent** [comment]
I have pushed a new version on homebrew. Can you confirm this is working well now?

**Comment by ddliugit** [comment]
I will try

**Comment by ddliugit** [comment]
The problem is not solved.
I post the problem in another topic:

https://github.com/stack-of-tasks/pinocchio/issues/709

**Comment by ddliugit** [comment]
See the https://github.com/stack-of-tasks/pinocchio/issues/709

Problem solved!!
Thanks
